version = 1

[[annotations]]
path = ["layouts/**", "data/xiv_*"]
SPDX-FileCopyrightText = "2024 Mathieu C. <mathieu@tx0.dev>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["README.md"]
precedence = "override"
SPDX-FileCopyrightText = "2024 Mathieu C. <mathieu@tx0.dev>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "static/xiv/**"
SPDX-FileCopyrightText = "© SQUARE ENIX CO., LTD. All rights reserved."
SPDX-License-Identifier = "LicenseRef-FFXIV-Materials-Usage"

[[annotations]]
path = ["assets/scss/_xiv_variables.scss", ".gitignore", "scripts/config.json"]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"


[[annotations]]
path = ["go.mod", "go.sum"]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "MIT"
