version = 1

[[annotations]]
path = ["layouts/**"]
SPDX-FileCopyrightText = "2024 Mathieu C. <mathieu@tx0.dev>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["README.md"]
precedence = "override"
SPDX-FileCopyrightText = "2024 Mathieu C. <mathieu@tx0.dev>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "static/xiv/**"
SPDX-FileCopyrightText = "© SQUARE ENIX CO., LTD. All rights reserved."
SPDX-License-Identifier = "LicenseRef-FFXIV-Materials-Usage"

[[annotations]]
path = ["go.mod"]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "MIT"
